name: Deploy to Vultr VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 45.76.154.13
          username: root
          password: W9[rTUQCX=%p4Dv)
          script: |
            cd /root/Sportzfx-NETWORK
            git pull origin main
            npm install
            pm2 restart server
